### ISSUE TITLE
Crash Issue: java.lang.NullPointerException

### ISSUE THREAD

**Issue by suerion** [Nasache/barklings-V1.21#2]
Bruh, this issue had got me a lot of grey hairs xD

Allways the CLient has disconnected with an Crash, had only found the issue with log4j2 settings.....

I love this mod, but after the debuging in an huge modpack, i had pulled out all  my hairs xD

https://mclo.gs/v4Iucoi#L2641

-> Crash Log with nothing 
https://mclo.gs/6PADrXh
https://mclo.gs/CAyHuts

-> Network Debug
https://mclo.gs/Ts4wUVF

Hope you could check your mod and fix the issue, without your Mod i could join the Server.

Fabric 0.16.5 Minecraft 1.21.1

**Comment by suerion** [comment]
Please enable Compatibility also with 
https://modrinth.com/mod/farmers-delight-refabricated

**Comment by suerion** [comment]
Again, Barkling let crash the Client..... with unexpected error...

Description: Unexpected error

java.lang.NullPointerException

https://mclo.gs/hLNk2hJ

Fabric 0.16.7 Minecraft 1.21.1
https://mclo.gs/Oh8nGW4

**Comment by suerion** [comment]
@Nasache

**Comment by suerion** [comment]
And Also, it crash on Opening Menu, and Creative Menu, etc... Random crash, it really annoying ;(

**Comment by suerion** [comment]
And it crash also, when the server stop, the client crash, it is allways, with barkling, after deleting it on my modpack, no issues,.....

**Comment by Nasache** [comment]
So sorry about this, looking into it a fix for this right now

**Comment by Nasache** [comment]
This should be fixed in the latest version, thank you for bringing this to my attention :)

**Comment by suerion** [comment]
@Nasache 

Sorry to pinging you, but i would use it that hard, it look so lovely :) and thanks for your update, :) i will test it
