### ISSUE TITLE
Nether dimension inaccessible

### ISSUE THREAD

**Issue by Slooshix** [Nasache/barklings-V1.21#3]
After a fix was found for the excessive spawn rate of barklings in the nether, it seems that barklings version 1.0.3 has locked access to entering the nether dimension completely. When attempting to enter the nether portal, it just forever displays the warping overlay and does not attempt to jump to the other dimension. I did test this with and without the mod installed and it does seem to be a consistent bug associated with the new version. I did comment this on the barklings curseforge page, but I figured I should leave an issue here too. I would love to see this addressed because it would be ironic if I have to undergo laggy crowded nether over not being able to enter it at all

**Comment by Nasache** [comment]
So sorry about this, looking into it right now

**Comment by Nasache** [comment]
I'm struggling to recreate this bug, in my testing the Nether is loading normally, do you have any other mods installed alongside Barklings? I can look for any potential problems between Barklings and another mod, but outside of that I'm not sure what could be causing this. I will continue looking though.
