### ISSUE TITLE
Names for some items are broken, also a suggestion for clovers!

### ISSUE THREAD

**Issue by Aruman-Zen** [Nasache/barklings-V1.21#5]
as the title says, here are the items:
![image](https://github.com/user-attachments/assets/ff763a1c-4148-4ef1-b244-f02c2044c770)

by using WTHIT Mod, it shows that bushes also don't have names
![image](https://github.com/user-attachments/assets/ccfcc2c1-6aab-4c35-b3d9-3bcdfe8ab9de)
![image](https://github.com/user-attachments/assets/86600ffd-fdd4-49f8-88c9-ca4162a00a40)
![image](https://github.com/user-attachments/assets/c1b496c8-b940-43db-9f7f-e642d25903eb)

those are all the items, but i also would like to suggest more uses for the clover flower
1. Make it so we can craft lime (or green) dye
2. Add clover to the flowers tag (just like vanilla pink petals)
3. Maybe we could use clover to make luck potion?

**Comment by Aruman-Zen** [comment]
actually if you could also add vanilla tags for all other items, that could be great to other mods that uses them

**Comment by Nasache** [comment]
Thank you! I'll get right on this :)

**Comment by Nasache** [comment]
Alright, the translations should be fixed, clover can now be crafted into lime dye, and it is correctly tagged as a flower now, thank you very much for the report!
