### ISSUE TITLE
Compatibility Issue since newest Update (All the wood weve got)  with Barklings on an huge Modpack [Fabric 1.21.1 and 0.16.9]

### ISSUE THREAD

**Issue by suerion** [Nasache/barklings-V1.21#7]
Hey, i had since the newest Update from "All the Wood we've got"  and  Compat issue with Barklings, i think it could be also an compat issue on

https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone and
https://github.com/Nasache/barklings-V1.21

https://github.com/Potion-Studios/All-The-Wood-Weve-Got/issues/9

latest.log
https://mclo.gs/2LEgvm8

crash report:
https://mclo.gs/aWq5997

**Comment by Nasache** [comment]
Thank you for reporting this! I'll look into the problem :)

**Comment by suerion** [comment]
Will close this issue, @Nasache because it is an issue from an Other mod, that had issued all mods here, but thanks for looking on it :)
